### ISSUE TITLE
ssl certificate for just-install.it

### ISSUE THREAD

**Issue by guiweber** [just-install/just-install#212]
It would be great to get an ssl certificate for just-install.it. It would make the initial installation more secure since the recommended way of installing just-install is to download the MSI from just-install.it. It is now possible to get free certificate through https://letsencrypt.org/ !

**Comment by lvillani** [comment]
This is currently not doable. The website is hosted on GitHub pages and they don't support HTTPS yet, AFAIK.

What I can do, however, is to put CloudFlare in front of the website, since they do offer free TLS certs/termination.

Also, I debate the usefulness of we also make just-install itself more secure: it doesn't even compare checksums of downloaded installers by default so there's more to do than making the initial install happen over TLS.

Also, I debate the

**Comment by guiweber** [comment]
I agree that it is not a solution to the whole security issue, but it is a critical first step forward. Yes, a large parts of the applications installed by just-install are downloaded over unencrypted links, but this is something that's slowly improving and we can work on updating the registry with https links as they are made available. Even if we don't do checksums, with TLS we can at least assume we got the data from the intended location. This is huge step forward and makes it much more difficult for an attacker to run a malicious script on your system.

Since Github pages with custom domain do not support https, another options would be to change the the download link to either a github.io link or use a github release where the latest version is uploaded. The install command would be something like:
`msiexec.exe /i https://lvillani.github.io/just-install/just-install.msi`
or
`msiexec.exe /i https://github.com/lvillani/just-install/releases/download/release_tag/just-install.msi`

**Comment by geek1011** [comment]
Also see just-install/registry#8

**Comment by lvillani** [comment]
We are now hosted by Netlify over TLS 🎉
