### ISSUE TITLE
just-install.it domain not available

### ISSUE THREAD

**Issue by maphew** [just-install/just-install#234]
http://downforeveryoneorjustme.com/just-install.it

> "It's not just you! http://just-install.it looks down from here."

**Comment by geek1011** [comment]
There are no A records on just-install.it right now for some reason.

**Comment by lvillani** [comment]
I opened a support ticket with OVH.

**Comment by lvillani** [comment]
Btw, it wasn't an OVH problem. After transfering the repo the org I didn't transfer the website outside the gh-pages branch of the just-install repo. I'm surprised that it survived for so long after the transfer. It should be working now.

**Comment by maphew** [comment]
domain is available, but http://just-install.it is now "404 There isn't a GitHub Pages site here."

**Comment by geek1011** [comment]
@lvillani Is there a reason why this file was missing?

**Comment by geek1011** [comment]
@maphew it should work now

**Comment by maphew** [comment]
yup all good, thanks!  

Not really related but good to know, Github.com "release" downloads are broken today. Includes things like Ghostscript. https://techcrunch.com/2017/02/28/amazon-aws-s3-outage-is-breaking-things-for-a-lot-of-websites-and-apps/

**Comment by lvillani** [comment]
@geek1011 I deleted the file. CNAME configuration should be done in the repo's settings page and the site should be served from https://github.com/just-install/just-install.github.io instead of this repo. Getting a 404 is a sign that it's probably a good time to have the site served from the other repo (it wouldn't let me otherwise). GitHub UI is confusing/confused when there's a mix of repos having the CNAME file there.

I'm going to remove the file again, wait for it to fail, switch over and contact GitHub support if it's still failing after that.

**Comment by lvillani** [comment]
It should be working (and being served from the new repo) now.
