### ISSUE TITLE
Support x86_64-only entries

### ISSUE THREAD

**Issue by lvillani** [just-install/just-install#235]
There are some programs that started shipping 64-bits only binaries (see https://github.com/just-install/registry/issues/10) and we don't support this kind of situation yet. i.e.: just-install assumes that an `x86` is always present (only `x86_64` is considered optional).

## To do
- [ ] Modify just-install to show a message when no 32 bit version is available on a 32 bit system
- [ ] Check for anything else that needs to be changed with just-install
- [ ] Update just-install registry JSON schema
- [ ] Update just-install customizer to show if an app is only for 64 bit

**Comment by geek1011** [comment]
I agree.

**Comment by geek1011** [comment]
I can work on this, but not until the middle of the month. I will add a checklist to your first post.

**Comment by guiweber** [comment]
Hey @lvillani @geek1011 , would you have some time to make this happen during Christmas? I could take care of everything related to the registry/updater : Updating the JSON schema and fixing all the problematic entries.

This issue is a bit annoying since it prevents our CI test suite to pass for the registry. It makes it hard to see if pull requests we receive are ok or not and if everything works as it should in general.

**Comment by geek1011** [comment]
@guiweber OK, I may work on this after I finish what I am working on right now. I've been quite busy though. I will get around to it sometime before the end of January I think.
