### ISSUE TITLE
why not "just-install upgrade"

### ISSUE THREAD

**Issue by nickreserved** [just-install/just-install#250]
Keep track what versions are installed and when run
just-install upgrade
makes a check if a newer version of all installed programs exist, and install again.

**Comment by geek1011** [comment]
Just-install is meant mainly for installing programs, not updating them. Most of the time, running just-install again will upgrade programs just fine.

There is no explicit upgrade command because it would make just-install way more complex (dealing with version checking, conflicts, registry format, etc), and because it is beyond the scope of just-install.

@lvillani and @guiweber, what do you think?

**Comment by guiweber** [comment]
Yes, the idea is to keep just-install simple. However I think we could keep this suggestion on our wish list if @lvillani concurs. I don't think it would be very complicated to keep a list of what has been installed through just-install and add an update command to install again if an updated version is available.

**Comment by lvillani** [comment]
Unfortunately handling upgrades and keeping track of what's installed on the system is outside the scope of just-install, especially with the few developers that can work on it at the moment.

* If just-install keeps track of what's installed on its own it may then may have a view of the world that is not synchronised with the system. What happens if you install something provided by just-install without using just-install?
* If you choose to integrate with Windows and the (Add/Remove list) you open another can of worms.

In my experience any Windows package manager that tries this fails horribly in one way or another, at the worst possible time. There are too many ways a program can be installed/upgraded/uninstalled on Windows.

I think that we shouldn't try be too smart unless we can find someone that can work full-time handling edge cases. I tried to describe why just-install is the way it is in [this blog post I authored five years ago](http://lorenzo.villani.me/2013/04/08/just-install-my-stuff/) when the project started.

Due to the above reasons, it's unlikely we'll ever implement this functionality. If you really need to handle upgrades I think it's better to investigate whether Chocolatey or Npackd can fulfil your needs.
