### ISSUE TITLE
Npackd

### ISSUE THREAD

**Issue by tim-lebedkov** [just-install/just-install#268]
are you interested in some kind of collaboration with Npackd?

--Tim

**Comment by geek1011** [comment]
What would it be about?

**Comment by tim-lebedkov** [comment]
If you look at the old issue https://github.com/just-install/just-install/issues/30 we already implemented a couple of things. If you have any ideas, please let me know.

In my opinion the next step could be a common naming convention for the packages. I would not suggest to rename the existing packages, but at least ensure that in the future the same package will get the same name in both package managers.

**Comment by sskras** [comment]
I though I wrote a comment yesterday (idea of libnpackd), but i can't see it today.  Was it deleted:)?

**Comment by lvillani** [comment]
I don't think we've ever deleted a comment.

**Comment by geek1011** [comment]
We never deleted a comment. GitHub now shows it if we delete or edit another person's comment, and there is also nothing in the audit logs for the organization.

**Comment by sskras** [comment]
(Thanks, probably my Chromebook ate it [was heavily oveloaded]. Since now I am free of fear of being anoying, there it is)

@tim-lebedkov in [his last comment in #30](https://github.com/just-install/just-install/issues/30#issuecomment-43549985) wrote:
> The next step in my opinion could be to reuse the data from the default Npackd repository in Just Install. Take a look at these XML files:

To which @lvillani replied:
> dealing with XML files and parsing formats different from just-install's simplistic format is really outside the scope of the project since I want something simple (< 1000 LOC) and maintainable.

Could it be solved in elegant way by spliting the needed code into something like libnpackd – a shared library?  So just-install could just install it (given the operator wants this:), load it dynamically and present a merged set of apps later.

Well, npackd itself (along with ncl) could link to it dynamically too.  No?

The only question I can think of is where to put libnacpkd / whether to export it's directory to the %PATH% .

**Comment by tim-lebedkov** [comment]
Npackd repository format is pretty simple, very similar to that of just-install so it would be easier to just write the code to load it in just-install than create a shared library. It would be even simpler to writer a converter that takes an Npackd repository and exports the data in just-install format.

**Comment by IviIIani** [comment]
Go away

**Comment by tim-lebedkov** [comment]
What was that?
![bildschirmfoto vom 2018-08-18 12-14-12](https://user-images.githubusercontent.com/831371/44298281-7a1e9a00-a2e0-11e8-821c-fbe976352866.png)

**Comment by lvillani** [comment]
A script kiddie creating a new account mimicking my username (replacing 'L's with 'I's) and posting random stuff to orgs, PRs and issues I'm involved with. He's gone now.

**Comment by lvillani** [comment]
We don't have the necessary bandwidth to handle this on our end for now. Closing. Feel free to reopen this in the future.
