### ISSUE TITLE
Add support for local installer files in registry and for http(s) URLs for -r

### ISSUE THREAD

**Issue by ooa113y** [just-install/just-install#294]
This would be extremely useful for installing software that cannot be added to the public registry for whatever reason (e.g. commercial), but that you have a local copy of. Currently, just-install fails to "connect" to such a file:// URL or a directly specified local path. Possibly related to #287.

**Comment by geek1011** [comment]
I see your point, although, in most situations wouldn't it be better to run a local web server for security and maintainability reasons?

**Comment by tlm-2501** [comment]
A temporary web-server does indeed work and is my current work-around for this issue (if anyone happens to be interested in doing the same thing, I'm using `php -S` with the PHP package which conveniently already is on JI). But hat makes this really awkward to use is that `just-install -r` doesn't accept a URL as of now. So if you want a custom repository, you currently have to juggle both a local file (the actual registry json file) *and* remote files (the installers). Having it work with a URL for the registry would actually make the web server idea more enticing because you can then keep your own registry up-to-date on your LAN. However, I don't see how this really adds any security -- I would actually argue it lessens it in home setup if a server is configured incorrectly and allows too much access (though it *would* help in a corporate set-up when someone can configure it properly).

**Comment by geek1011** [comment]
> A temporary web-server does indeed work and is my current work-around for this issue (if anyone happens to be interested in doing the same thing, I'm using php -S with the PHP package which conveniently already is on JI).
Yep. I personally prefer python (in j-i) or caddy.

> But what makes this really awkward to use is that just-install -r doesn't accept a URL as of now. So if you want a custom repository, you currently have to juggle both a local file (the actual registry json file) and remote files (the installers).
@lvillani?

> This isn't completely awful. It works fine, but updating the registry will be a manual process and it will be out of sync with the one in the web server, unless you're running the server on the same machine where the registry file already is (then you can just specify the local path to the registry).
However, on previous versions of Windows, curl is not built-in.
Good point. I'm usually use Linux or MinGW, so I keep forgetting how bad the windows command line is.

> All that said, I don't see how this really adds any security -- I would actually argue it lessens it in home setup if a server is configured incorrectly and allows too much access (though it would help in a corporate set-up when someone can configure it properly).
Yes, I assumed this was for enterprise use, in which having the installers centrally managed instead of somewhere they can be manipulated by users.

**Comment by lvillani** [comment]
Agreed, we should uniformly support both local and remote sources.

**Comment by lvillani** [comment]
See #287
