### ISSUE TITLE
Add pre and post install scripts

### ISSUE THREAD

**Issue by mimi89999** [just-install/just-install#307]
This feature would allow a clean work arround for various installer issues. I hope that that feature is in the scope of this project. If it is, I could try to implement that feature. I would really like to be able to install all the apps I need with just-install.

**Comment by lvillani** [comment]
Can you provide an example of why this is needed?

**Comment by mimi89999** [comment]
Currently it could solve the issue with installers requireing config files. Postinstall could be used to add shortcuts in start menu for unzipped apps. There are many other possible use cases.

**Comment by lvillani** [comment]
This will make auditing the default registry harder, due to the ability to add arbitrary commands in these hooks. We don't have the resources to handle this additional load. I, in particular, don't have a Windows machine always at my disposal to test incoming changes.

just-install is all about hard-coded defaults that cover 80% of what we need, doing 20% of the work. Despite that we struggle to handle what we have with our limited time.

Unfortunately, we cannot add every feature. Some features are small in terms of code but require a larger effort to maintain down the road. We cannot satisfy everyone, and I have to say "No" to new features _very_ often 😅.

If you need to invoke arbitrary commands I'd suggest you to call just-install from a script and do your pre/post processing there.

We may re-evaluate adding this feature in the future but for now we're not going to add it.

**Comment by geek1011** [comment]
> If it is, I could try to implement that feature. I would really like to be able to install all the apps I need with just-install.

You could maintain a personal fork with that feature, and use something like [json-patch](https://github.com/evanphx/json-patch) (or even something custom) to apply your changes to the registry. I'd say it would take at most an hour of work to add install scripts (just add a field to the registry with an array of commands (split the arguments into an array) to run with `exec.Command(args...).Run()`)

> We don't have the resources to handle this additional load. I, in particular, don't have a Windows machine always at my disposal to test incoming changes.

^. Most of the j-i development I do is on Linux too (in fact, jiup-go hasn't even been edited on Windows by me before). I use j-i to automate the installs of my Windows VMs for testing and for the rare occasions I actually need a Windows install (which I usually get rid of soon after).

**Comment by mimi89999** [comment]
I changed my strategy and will try to add most functionality directly to _just-install_. I'm using them for common tasks that I think _j-i_ should support and will implement that and open PRs.

I'm also working exclusively on GNU/Linux. O only have a VM for testing. I'm working as a sysadmin and need j-i for automatically deploying software on ~100 computers.

**Comment by geek1011** [comment]
@mimi89999 Have you considered wrapping the installers/zips with Inno setup, then deploying those with j-i? Inno setup has an option to not create uninstall info (which is useful for wrapping installers), and it also has a relatively simple source format (I wrote a simple Go generator for it a while ago). It would probably be easier in the long term to write an automated repacker/wrapper which generates Inno installers rather than adding every possible feature to j-i. Also, Inno works perfectly in Wine, which means you can continue working exclusively in Linux.

**Comment by mimi89999** [comment]
@geek1011 I was considering WiX as it has the advantage of building MSI packages. They have many advantages including the possibility of deploying them with GPO. One argument against them might be that Microsoft hasn't updated MSI for quite some time and most likely plans to replace them with MSIX, but Microsoft has a long history of keeping legacy technologies, so that probably will not be an issue for quite some time.

The reason why I chose not to do that is that it is much easier to add a pre/post script that to package several apps on each new release. Surely, that could be automated, but writing scripts for that would require most effort. There is also a community around projects like j-i that could be leveraged. Many if not most issues in the repo will probably get fixed before I notice them. When packing/repacking/wrapping I would probably be doing everything on my own 99% of the time. I haven't found any repo with packaging scripts or packages that could be trusted. I won't install the first result that appears when searching for _{softwareName} MSI_ or anything similar.

**Comment by geek1011** [comment]
@mimi89999 That's why I suggested Inno. Wix is nice, but it's extremely complicated and error-prone to do any custom actions in MSI files.

Regarding your point about j-i issues being fixed and saving time, j-i has barely been keeping up with the issues, as neither I nor @lvillani use Windows enough to justify spending large amounts of time on j-i (most of the work is done whenever we need Windows for some reason). For the purposes of making shortcuts, a dedicated installer like Inno Setup will also have bugs fixed and so on. That allows you to separate the packaging from the deployment.

For repacking with Inno, I just generate an Inno config from my own JSON config and the source files with a Go tool, and then compile it with iscc in Wine.

**Comment by mimi89999** [comment]
@geek1011 I would disagree. Upstream changing anything (download URL, installer or even executable name) might disturb custom packaging and that would probably only be noticed after being reported by users. _j-i_ registry gets updated by contributors, so any such issue will probably get fixed rather fast.

Of course, best would be to get upstream to do that, but I am not too optimistic about that. Some vendors like JetBrains think that config files aren't an issue. IMHO requiring the for all types of install and not having defaults is insane. Some projects seem half dead or full of issues, so fixing the installer is probably the least of their priorities. I think that it is very unlikely that they will accept any contribution requiring changes on their server. Some FOSS projects prioritize GNU/Linux and don't really care about Windows, so it would also be difficult to get anything from them.

**Comment by geek1011** [comment]
@mimi89999 You could do something in-between by using the j-i registry (j-i has it in a separate package) as the source for repackaging.

**Comment by mimi89999** [comment]
@geek1011 There are probably many options. I think that my contributions to _j-i_ might also benefit the entire community. That's also a reason why I am making them. Nobody besides you and @lvillani commented under those issue. Evaluating where users want a feature might be difficult without feedback.
