### ISSUE TITLE
Add start menu liniks for zip installers

### ISSUE THREAD

**Issue by mimi89999** [just-install/just-install#310]
If it is in the scope of the project, I can open a PR for it.

**Comment by lvillani** [comment]
Closing as out of scope. See also https://github.com/just-install/registry/issues/181.

**Comment by mimi89999** [comment]
Is it really so much out of scope? A program isn't quite usable if users can't find it.

**Comment by lvillani** [comment]
If upstreams cared about Start Menu entries, they would ship proper installers instead of a bunch of binaries in a zip file. Our job is to fetch something and install it, which in the case of ZIP files means extracting them somewhere. If we start creating `.lnk` files we turn into yet another bespoke installer.

**Comment by mimi89999** [comment]
But extracting an app to `Program Files` doesn't quite mare it usable. You have to know the path and navigate there. Why do you think that adding a single link will turn _just-install_ into another _bespoke installer_? It would just be extracting an archive and creating a link. Nothing simpler. The equivalent of two commands.

**Comment by lvillani** [comment]
Re-opening this issue since I'm re-evaluating adding this after seeing #313
