### ISSUE TITLE
windows 7 not working

### ISSUE THREAD

**Issue by PantACRO4life** [just-install/just-install#315]
Ive been using it for quite while now, I am doing test to upgrade 300 computer and I notice it doesnt install correctly on win7

looking foward for an answer asap !! 

thanks and good work

**Comment by mimi89999** [comment]
What's the issue exactly? What program doesn't install?

**Comment by PantACRO4life** [comment]
just-install itself is not installing with msiexec or and manual installation work but cannot install 7zip

**Comment by mimi89999** [comment]
Are you installing it in `cmd` run as `Administrator`?

**Comment by PantACRO4life** [comment]
.. oc

**Comment by PantACRO4life** [comment]
![image](https://user-images.githubusercontent.com/6643071/75048702-f32f1c80-5496-11ea-94ba-52b8705f2dc0.png)

**Comment by PantACRO4life** [comment]
note that this is a none-upgraded windows 7 on a ESXi hypervisor only for testing deployement

**Comment by PantACRO4life** [comment]
![image](https://user-images.githubusercontent.com/6643071/75048863-37bab800-5497-11ea-81c2-fcdf1b9e1752.png)

**Comment by lvillani** [comment]
In my experience that’s a TLS negotiation issue. GitHub stopped serving anything less than TLS 1.2 [a couple of years ago](https://github.blog/2018-02-01-crypto-removal-notice/) and as far as I know unpatched Windows 7 doesn’t ship with TLS 1.1 or TLS 1.2 enabled out of the box. For example even IE 8 inside a clean Windows 7 VM is unable to connect to some HTTPS sites these days.

[This document](https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi) might be helpful even though I haven’t tried it personally since I bootstrap just-install in such an old environment by other means.

Additionally, consider that consumer support for Windows 7 from Microsoft has ended January 14 2020. Consequently, we may also end up dropping support for said version of Windows in the near future.

**Comment by PantACRO4life** [comment]
ok thanks, and yes that why we upgrading our clients
